config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'questions#index'

  get 'users/authorize/new', to: 'users#new_authorized'
  post 'users/authorize/create', to: 'users#create_authorized'

  post '/search', to: 'searches#search'

  resources :questions do
    post :comment_question, to: 'comments#comment_question'
    member do
      delete :remove_attachment
      post :subscribe
    end
    resources :answers do
      post :comment_answer, to: 'comments#comment_answer'
      member do
        post :set_best
        patch :upvote
        patch :downvote
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :all, on: :collection
      end
      resources :questions do
        resources :answers, only: %i[index create]
      end
      resources :answers, only: :show
    end
  end

  mount ActionCable.server => '/cable'

  match '*path' => redirect('/'), via: :get
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, :body, presence: true
  has_many :answers, dependent: :delete_all
  has_many :attachments, as: :attachable, dependent: :delete_all
  has_many :comments, as: :commentable, dependent: :delete_all
  has_many :subscriptions, dependent: :delete_all

  default_scope { order(created_at: :desc) }

  accepts_nested_attributes_for :attachments

  def short_body
    "#{body.truncate(57)}..."
  end

  def user
    User.find(user_id).email
  end

  def route
    Rails.application.routes.url_helpers.question_path(self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :authenticate_user!, only: :create

  def index
    @questions = Question.all
    respond_with @questions, adapter: :json, each_serializer: QuestionSerializer
  end

  def show
    respond_with Question.find(params[:id]), adapter: :json, serializer: LoneQuestionSerializer
  end

  def create
    if can?(:create, Question)
      respond_with Question.create(question_params), adapter: :json
    else
      render json: { message: 'Not enough permissions' }, status: :forbidden
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :find_question, only: %i[show edit update destroy publish_question subscribe]
  before_action :find_answers, only: :show

  after_action :publish_question, only: %i[create]

  respond_to :js, :html

  authorize_resource :question
  authorize_resource :answer

  def publish_question
    return if @question.errors.any?

    json = @question.attributes.merge('current_user' => (user_signed_in? ? current_user.to_json : '0'),\
                                      'short_body' => @question.short_body,\
                                      'question_path' => question_path(@question),\
                                      'user' => @question.user)
    ActionCable.server.broadcast 'question_channel', json
  end

  def index
    respond_with(@questions = Question.all)
  end

  def show
    respond_with @question
  end

  def new
    respond_with(@question = Question.new)
  end

  def create
    @question = Question.create(questions_params.merge('user_id' => current_user.id))
    current_user.subscriptions.create(question_id: @question.id)
    respond_with(@question)
  end

  def update
    @question.update(questions_params)
    respond_with @question
  end

  def destroy
    respond_with(@question.destroy)
  end

  def remove_attachment
    @question = Question.find(params[:id])
    Attachment.find(params[:attachment_id]).destroy
  end

  def subscribe
    @subscription = current_user.subscriptions.where(question: @question).first
    if @subscription
      @subscription.destroy
      @subscription = nil
    else
      @subscription = current_user.subscriptions.create(question: @question)
    end
  end

  private

  def questions_params
    params.require(:question).permit(:title, :body, :attachment_id, attachments_attributes: [:file])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def find_answers
    @answers = @question.answers
    @answer = Answer.new(question: @question) if user_signed_in?
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer.html.slim
- cache answer do
  div class = (["answer", answer.best ? "green" : ""])
    div.vote
      a {href = upvote_question_answer_path(question, answer)
        data-method = "patch"
        data-remote = "true"
        class="vote-button" }
          = fa_icon "arrow-up", class: "upvote upvote-#{answer.id} #{'active-upvote' if answer.upvoted?(current_user)}"
      p class = 'score-#{answer.id}' = answer.total_score
      a {href = downvote_question_answer_path(question, answer)
        data-method = "patch"
        data-remote = "true"
        class="vote-button" }
        = fa_icon "arrow-down", class: "downvote downvote-#{answer.id} #{'active-downvote' if answer.downvoted?(current_user)}"
    div class = (["answer-#{answer.id} answer-body"])
      h5 = answer.user
      p class = "body-#{answer.id}" = answer.body
      - if can?(:create, Question)
        = form_for([question, answer], remote: true, html: { class: "answer-form-#{answer.id} answer-form" }) do |f|
          = f.label :body, "Answer", hidden: true
          = f.text_area :body
          = f.submit "Save"
        div class = "additions"
          div.attachments
            p Attachments:
            ul class = "list-answer-#{answer.id} list-answer"
              - answer.attachments.each do |at|
                - unless at.new_record?
                  li
                    = link_to at.name, at.file.url
                    = render 'questions/remove_form', question: question, attachment: at
          div class = "answer-#{answer.id}-comments answer-comments"
            p Comments:
            ul class = "answer-comment-list answer-#{answer.id}-comment-list"
              - answer.comments.each do |c|
                - unless c.new_record?
                  li
                    span = "#{c.user.email}: "
                    = "#{c.body}"
            = form_tag question_answer_comment_answer_path(question, answer), class: "add-comment-form-#{answer.id} answer-comment-form", remote: true do
              = text_field :comment, :body
              = submit_tag 'Comment'
        div.actions-wrapper
          hr
          div.actions
            - if can?(:comment_answer, Comment)
              a class = "add-comment-answer-#{answer.id} add-comment-answer" Add comment
            - if can?(:update, answer)
              = link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
            - if can?(:destroy, answer)
              = form_tag question_answer_path(answer.question, answer), method: :delete, remote: true do |f|
                = submit_tag 'Delete', id: 'select'
            - if can?(:set_best, answer)
              = form_tag set_best_question_answer_path(question, answer), remote: true do
                = submit_tag 'Select as the best', id: 'select'

app/views/questions/_attachments.html.slim
- @question.attachments.each do |a|
  - cache a do
    - unless a.new_record?
      li
        = link_to a.name, a.file.url
        = render 'remove_form', question: @question, attachment: a

app/views/questions/_comments.html.slim
- @question.comments.each do |c|
  - cache c do
    - unless c.new_record?
      li
        span = "#{c.user.email}: "
        = "#{c.body}"

app/views/questions/_edit_form.html.slim
= form_for(@question, remote: true, html: { class: 'edit-question-form', style: 'display:none;' }) do |f|
  = f.label :title, hidden: true
  = f.text_field :title, class: 'edit-title'
  = f.label :body, hidden: true
  = f.text_area :body, class: 'edit-body'
  div.bottom-wrapper
    a href='' class="add-file" Add file
    div.files
      = f.fields_for(:attachments, @question.attachments.build) do |a|
        div.add-file-form style='display: none;'
          = a.label :file
          = a.file_field :file, class: 'file'
    = f.submit 'Save', class: 'file-submit'

app/views/questions/_form.html.slim
= form_for @question do |f|
  div.form-group
    = f.label :title
    br
    = f.text_field :title
  div.form-group.mt-3
    = f.label :body
    br
    = f.text_area :body
  div.form-group.mt-3
  div.files
    = f.fields_for(:attachments, @question.attachments.build) do |a|
      div.add-file-form
        = a.label :file, class: 'file-label'
        = a.file_field :file, class: 'file-new'
  = f.submit 'Ask!'

app/views/questions/_question.html.slim
tr
  td = question.title
  td = question.short_body
  td = question.user
  td = link_to 'Show', question_path(question)
  - if can?(:destroy, question)
    td = link_to 'Destroy', question_path(question), method: :delete

app/views/questions/_remove_form.html.slim
- if can?(:destroy, Attachment)
  div.delete-form
    = form_tag remove_attachment_question_path(id: question.id, attachment_id: attachment.id),method: :delete, remote: true, class: 'delete-form' do
      = submit_tag "\u274C", id: 'delete'

app/views/questions/index.html.slim
div.container-fluid
  table.table.table-bordered
    thead.table-dark
      tr
        th Title
        th Body
        th Author
        th
        th
    tbody class = 'questions_list'
    = render @questions
  - if can?(:create, Question)
    p = link_to 'Ask a question', new_question_path

app/views/questions/new.html.slim
div.container
  = render 'form'

app/views/questions/remove_attachment.js.erb
$('.list').html('');
$('.list-answer').html('');
<% @question.attachments.each do |a| %>
$('.list').append('<li><%= link_to a.name, a.file.url %> <%= render 'remove_form',question: @question, attachment: a %></li>')
<% end %>
<% @question.answers.each do |ans| %>
<% ans.attachments.each do |a| %>
$('.list-answer-<%= ans.id %>').append('<li><%= link_to a.name, a.file.url %> <%= render 'remove_form',question: @question, attachment: a %></li>')
<% end %>
<% end %>

app/views/questions/show.html.slim
- cache @question do
  div.container
    div class = "question" data-title = 'question_id' data-content = "#{@question.id}"
      h1 class= 'question-title' = @question.title
      h3 class= 'question-body' = @question.body
      - if can?(:update, Question)
        = render 'edit_form'
        div.question-actions
          = link_to 'Edit', '', class: 'edit-question-link'
          - if can?(:subscribe, Question)
            = form_tag
              = label_tag :subscribed
              = check_box_tag :subscribed, 1 ,current_user.subbed?(@question)
      - if @question.attachments.any?
        div.additions
          div.attachments
            p Attachments:
            ul.list
              = render 'attachments'
          div.question-comments
            p Comments:
            ul.question-comment-list
              = render 'comments'
            - if can?(:comment_question, Comment)
              a.add-comment Add comment
              = form_tag question_comment_question_path(@question), class: 'add-comment-form', remote: true do
                = text_field :comment, :body
                = submit_tag 'Comment'
      hr
    div.answers
      - if @answers.where(best: true).size > 0
        = render partial: 'answer', locals: { answer: @answers.where(best: true)[0] , question: @question}
      - @answers.each do |a|
        - unless a.best?
          = render partial: 'answer', locals: { answer: a , question: @question}
    - if user_signed_in?
      div.new_answer_wrapper
        = form_for([@question, @answer], remote: true) do |f|
          div.form-group
            = f.label :body, 'Your answer: '
            div.errors
            = f.text_area :body, class: 'form-control new-answer-body'
            div.bottom-wrapper
              a href='' class="add-file-answer" Add file
              div.files
                = f.fields_for(:attachments, @answer.attachments.build) do |a|
                  div.add-file-form-answer style='display: none;'
                    = a.label :file
                    = a.file_field :file, class: 'file'
          = f.submit 'Submit', class: 'btn btn-primary mt-3'
    - else
      p
        = link_to 'Login ', new_user_session_path
        = "in order to post answers!"

app/views/questions/subscribe.js.erb
<% if @subscription %>
alert('subscribed!')
<% else %>
alert('unsubscribed!')
<% end %>

app/views/questions/update.js.erb
<% if @question.errors.present? %>
<% @question.errors.full_messages.each do |msg| %>
$('.errors').append('<%= j msg %>!')
$('.errors').css('color', 'red')
<% end %>
<% else %>
$('.question-title').html('<%= @question.title %>')
$('.question-body').html('<%= @question.body %>')
$('.question-title').show()
$('.question-body').show()
$('.list').html('');
$('.list-answer').html('');
<% @question.attachments.each do |a| %>
$('.list').append('<li><%= link_to a.name, a.file.url %> <%= render 'remove_form',question: @question, attachment: a %></li>')
<% end %>
<% @question.answers.each do |ans| %>
<% ans.attachments.each do |a| %>
$('.list-answer-<%= ans.id %>').append('<li><%= link_to a.name, a.file.url %> <%= render 'remove_form',question: @question, attachment: a %></li>')
<% end %>
<% end %>
$('.edit-question-form').hide()
if ($('.edit-question-link').hasClass('cancel')) {
    $('.edit-question-link').html('Edit');
    $('.edit-question-link').removeClass('cancel');
} else {
    $('.edit-question-link').html('Cancel');
    $('.edit-question-link').addClass('cancel');
}
<% end %>