config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'questions#index'

  get 'users/authorize/new', to: 'users#new_authorized'
  post 'users/authorize/create', to: 'users#create_authorized'

  post '/search', to: 'searches#search'

  resources :questions do
    post :comment_question, to: 'comments#comment_question'
    member do
      delete :remove_attachment
      post :subscribe
    end
    resources :answers do
      post :comment_answer, to: 'comments#comment_answer'
      member do
        post :set_best
        patch :upvote
        patch :downvote
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :all, on: :collection
      end
      resources :questions do
        resources :answers, only: %i[index create]
      end
      resources :answers, only: :show
    end
  end

  mount ActionCable.server => '/cable'

  match '*path' => redirect('/'), via: :get
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qna</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">
          <i class="fa fa-home"></i>
          Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
    </ul>
    <ul class="navbar-nav ">
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        <% else %>
          <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
        <% end %>
        <i class="fa fa-globe">
          <span class="badge badge-success"></span>
        </i>
      </li>
    </ul>
    <%= form_tag search_path, class: 'form-inline my-2 my-lg-0' do %>
      <%= text_field_tag :search,"", class: 'form-control mr-sm-2' %>
      <%= select_tag :type, options_for_select(Search.searchables, Search.searchables.first), class: 'form-control mr-sm-2' %>
      <%= submit_tag 'Search', class: 'btn btn-outline-success my-2 my-sm-0' %>
    <% end %>
  </div>
</nav>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
</body>
</html>